In [1]:
from pandas import read_csv, isna

In [2]:
df = read_csv("HN_posts_year_to_Sep_26_2016.csv")

In [3]:
df.head()

,id,title,url,num_points,num_comments,author,created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14

In [4]:
df.columns

Index(['id', 'title', 'url', 'num_points', 'num_comments', 'author',
       'created_at'],
      dtype='object')

In [5]:
df.__len__()

293119

In [6]:
df.drop_duplicates(inplace= True)

In [7]:
df.__len__()

293119

In [8]:
lst_columns = []
for i in df.columns :
    lst_columns.append(i.capitalize())
lst_columns

['Id', 'Title', 'Url', 'Num_points', 'Num_comments', 'Author', 'Created_at']

In [9]:
df.columns = lst_columns

In [10]:
df.head()

,Id,Title,Url,Num_points,Num_comments,Author,Created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14

In [11]:
# finding the columns with Nan Values in it :
lst_column_with_nan_values  = []
for i in df.columns :
    if df[isna(df[i])].__len__() != 0 :
        lst_column_with_nan_values.append(i)
lst_column_with_nan_values

['Url']

In [18]:
df[isna(df["Url"])]

,Id,Title,Url,Num_points,Num_comments,Author,Created_at
10,12578908,Ask HN: What TLD do you use for local developm...,NaN,4,7,Sevrene,9/26/2016 2:53
42,12578522,Ask HN: How do you pass on your work when you ...,NaN,6,3,PascLeRasc,9/26/2016 1:17
56,12578186,Job app website farms my social network links....,NaN,1,1,macscam,9/26/2016 0:02
76,12577908,Ask HN: How a DNS problem can be limited to a ...,NaN,1,0,kuon,9/25/2016 22:57
80,12577870,Ask HN: Why join a fund when you can be an angel?,NaN,1,3,anthony_james,9/25/2016 22:48
...,...,...,...,...,...,...,...
293052,10177317,Ask HN: Any meteor devs out there who could sp...,NaN,2,1,louisswiss,9/6/2015 10:52
293055,10177309,Ask HN: Any recommendations for books about ra...,NaN,2,4,rationalthrowa,9/6/2015 10:46
293073,10177200,Ask HN: Where do you look for work if you need...,NaN,14,20,coroutines,9/6/2015 9:36
293074,10177186,Tell HN: Comment counts on list pages are broken,NaN,7,1,aw3c2,9/6/2015 9:27
293114,10176919,Ask HN: What is/are your favorite quote(s)?,NaN,15,20,kumarski,9/6/2015 6:02

In [19]:
lst_exception_rows = []
lst = []
for i in df["Author"] :
    lst.append(i.capitalize())
lst_exception_rows

[]

In [20]:
lst

['Altstar',
 'Blacksqr',
 'Pavel_lishin',
 'Poindontcare',
 'Markgainor1',
 'Bdoux',
 'Thecodrr',
 'Thecodrr',
 'Jandll',
 'Mynameislegion',
 'Sevrene',
 'X43b',
 'Rachelf',
 'Srt32',
 'Ttam',
 'Lind5',
 'Phodo',
 'Yarapavan',
 'Thevet',
 'Muratmutlu',
 'Adamnemecek',
 'Colinprince',
 'Kawera',
 'V3ss0n',
 'Luu',
 'Kawera',
 'Mynameislegion',
 'Samclemens',
 'Dredmorbius',
 'Samber',
 'Blondie9x',
 'Happy-go-lucky',
 'Peterkor',
 'Execcoach',
 'Danso',
 'Bane',
 'Guia',
 'Rocky1138',
 'Megamike48',
 'Jonbaer',
 'Jonbaer',
 'Jonbaer',
 'Pasclerasc',
 '3manuek',
 'Gw5815',
 'Shenglong',
 'Upen',
 'Dinahdavis',
 'Greg7mdp',
 'Abuggia',
 'Kareemm',
 'Prostoalex',
 'Saamm',
 'Jseliger',
 'Dinahdavis',
 'Bootload',
 'Macscam',
 'Koshkin',
 'Christinecha',
 'Helloworld',
 'Itonula',
 'Benaadams',
 'Prostoalex',
 'Visionp',
 'Grondilu',
 'Dools',
 'Meanduck',
 'Ftclausen',
 'Geodel',
 'Prostoalex',
 'Dbranes',
 'Innovationanarc',
 'Dkarapetyan',
 'Daegloe',
 'Innovationanarc',
 'Dangoldin',
 'Kuon',
 'Matttse',
 'Sacheendra',
 'Tsiolkovsky',
 'Anthony_james',
 'My_first_acct',
 'Jboyozette',
 'Altstar',
 'Confiscate',
 'Nerdsmagazine',
 'Severine',
 'Severine',
 'Kawera',
 'Stevewilhelm',
 'Nicojuicy',
 'Type0',
 'Sunils34',
 'Evo_9',
 'Llazzaro',
 'Cpeterso',
 'Allsystemsgo',
 'Type0',
 'Lefticus',
 'Robin_reala',
 'Platz',
 'Archgoon',
 '00taffe',
 'Dnetesn',
 'Michaelao',
 'Otoolep',
 'Dcgudeman',
 'Kornish',
 'Bbyford',
 'Nickcw',
 'Kawera',
 'Smb06',
 'Waqasaday',
 'Silvialisam',
 'Adamnemecek',
 'Aaronyy',
 'Silvialisam',
 'Mpweiher',
 'Pwdisswordfish',
 'Waqasaday',
 'Zura',
 'Hooke',
 'Mpweiher',
 'Rosser',
 'Kiyanwang',
 'Sethbannon',
 'Lorax',
 'Conorpp',
 'Hrgeek',
 'Rahuly247',
 'Akkartik',
 'Rovercaps',
 'Rovercaps',
 'Pera',
 'Simonebrunozzi',
 'Prostoalex',
 'Zos',
 'Prostoalex',
 'Prostoalex',
 'Rmason',
 'Ryderj',
 'Seanmavley',
 'Danielam',
 'Jgraber',
 'Lukego',
 'Wyoh',
 'Ayw',
 'Samber',
 'Insalgo',
 'Jonathanmh',
 'Avadhoot',
 'Mjhea0',
 'Walterbell',
 'Tachion',
 'Jsnell',
 'Fraqed',
 'Smollett',
 'Upen',
 'The-enemy',
 'Bpierre',
 'Raimue',
 'Btrask',
 'Silvialisam',
 'Dewey',
 'Silvialisam',
 'Zo7',
 'Sunnykgupta',
 'Hkt',
 'Stanislavb',
 'Clintehrlich',
 'Eth0up',
 'Ziggystardust',
 'Prostoalex',
 'Pvsukale3',
 'Vladgh',
 'Sjellis',
 'Muhic',
 'Soulchild37',
 'Kushti',
 'Muhic',
 'Plurby',
 'Alexellisuk',
 'Muhic',
 'Pvsukale3',
 'Muhic',
 'Wanderer42',
 'Plurby',
 'Muhic',
 'Plurby',
 'Muhic',
 'Pvsukale3',
 'Muhic',
 'Fiatjaf',
 'Walkingolof',
 'Turingbook',
 'Walterbell',
 'Mazsa',
 'Alonisser',
 'Danielrm26',
 'Jcdavis',
 'Ingve',
 'Rmason',
 'Fiatjaf',
 'Pmcpinto',
 'Prostoalex',
 'Giis',
 'Rmason',
 'Jseliger',
 'Elmar',
 'Dazbradbury',
 'Pmcpinto',
 'Prostoalex',
 'Llvllatrix',
 'Codepsycho',
 'Giis',
 'Chirau',
 'Npongratz',
 'Misnamed',
 'Misnamed',
 'Danso',
 'Moks',
 'M_grey',
 'Jseliger',
 'A_endurance',
 'Paulpauper',
 'Endswapper',
 'Endswapper',
 'Evo_9',
 'Baq',
 'Paulpauper',
 'Fiatjaf',
 'Askafriend',
 'Cosmoharrigan',
 'Zerognowl',
 'Infoqr',
 'Priyankasingh',
 'Mihaipetre',
 'Paulpauper',
 'Okket',
 'Abaschin',
 'Iamd3vil',
 'Zerognowl',
 'Ajani',
 'Paulpauper',
 'Dsr12',
 'Necrodome',
 'Keepingscore',
 'Paulpauper',
 'Mboelen',
 'Vilhelm_s',
 'Jdimov10',
 'Paulpauper',
 'Practicalswift',
 'Panic',
 'Paulpauper',
 'Intrasight',
 'Wanderer42',
 'Arjun27',
 'Jerry2',
 'Hillarybriss',
 'Posternut',
 'Firasd',
 'Lucasmreis',
 'Morgangiraud',
 'Victordw',
 'Dwaxe',
 'Aziaziazi',
 'Andreapaiola',
 'Gskpsy',
 'Tapan_pandita',
 'Kinnard',
 'Hacknat',
 'Pweissbrod',
 'Petethomas',
 'Sztwiorok',
 '11thearlofmar',
 'Mathgenius',
 'Tefo-mohapi',
 'Philk10',
 'Gerardforde',
 'Codegeek',
 'Ohjeez',
 'Csallen',
 'Azuajef',
 'Nhumrich',
 'Nefitty',
 'Mynameislegion',
 'Mrexodia',
 'Jsnell',
 'Skolos',
 'Linalaunebaer',
 'Kawera',
 'Qaq',
 'Wanderer42',
 'Fagnerbrack',
 'Makmanalp',
 'Benevol',
 'Engi_nerd',
 'Ry4n413',
 'Nfixx',
 'Sonabinu',
 'Nneonneo',
 'Posternut',
 'Jseliger',
 'Maxwell',
 '0uate',
 'Boduh',
 'Tx3',
 'Hellofunk',
 'Kardashian007',
 'Agumonkey',
 'Upen',
 'Keirthomas',
 'Jownwayne',
 'Mishigiber',
 'Fspacef',
 'Dardien',
 'Knawade',
 'Mawais999',
 'Fitzwatermellow',
 'Upen',
 'Sudheendrach',
 'Sjreese',
 'Henck',
 'Sjreese',
 'Chwolfe',
 'Jasamba',
 'Beweinreich',
 'Blondie9x',
 'Robin_reala',
 'Halninethousand',
 'Elpoisterio',
 'Aurelian15',
 'Vtorosyan',
 'Chmars',
 'Yummyfajitas',
 'Dowwie',
 'Aiw1nt3rs',
 'Rfreytag',
 'Posternut',
 'Cjlm',
 'Restapi',
 'Daredave',
 'Marcusgarvey',
 'Tristanac',
 '0x0',
 'Tvnfo',
 'Velodrome',
 'Mbertschler',
 'Juusaw',
 'Sajid',
 'Forgottenacc56',
 'Shazad',
 'Dsr12',
 'Bootload',
 'Sql2219',
 'Ed-bit',
 'Samber',
 'Danso',
 'Glaberficken',
 'Dsr12',
 'Jonbaer',
 'Samber',
 'Joss82',
 'Adventured',
 'Yangshuo215',
 'Rkwz',
 'Dnetesn',
 'Srikar',
 'Kschua',
 'Shubhamjain',
 'Rcarmo',
 'Backtobasics',
 'Argonlaser',
 'Hunglee2',
 'What_doyouthink',
 'Hunglee2',
 'Bglad01',
 'Gexos',
 'Jamesfisher',
 'Reddotx',
 'Jerry2',
 'Aburan28',
 'Nkurz',
 'Andreapaiola',
 'Nfixx',
 'Vivekrajagarwal',
 'Xzetau8',
 'Allendoerfer',
 'Robin_reala',
 'Thecustardking',
 'Sfjulie',
 'Bootload',
 'Known',
 'Rgun',
 'Okket',
 'Github-cat',
 'Sergeant3',
 'Kardashian007',
 'Compil3r',
 'Doomhz',
 'Usu',
 'Miiiiiike',
 'Dpatru',
 'Fagnerbrack',
 'Fagnerbrack',
 'Fagnerbrack',
 'Ivanzone',
 'Bootload',
 'Bootload',
 'Selmat',
 'Octoploid',
 'Sylvainkalache',
 'Phatak-dev',
 'Walterbell',
 '2a0c40',
 'Dturnbull',
 'Patatino',
 'Kardashian007',
 'Boramalper',
 'Xpaw',
 'Leafie',
 'Eddywashere',
 'Tempestn',
 'Dsr12',
 'Achanda358',
 'Chipz',
 'Preetish',
 'Vpj',
 'Walterbell',
 'Dsr12',
 'Selmat',
 'Agsw',
 'Velmu',
 'Known',
 'Binaryidiot',
 'Fokker',
 'Daiwb',
 'Ciconia',
 'Pkop',
 'Agsw',
 'Woliveirajr',
 'Vasu1711',
 'Flailfast',
 'Samber',
 'Nurdok',
 'Dredmorbius',
 'Dingdongding',
 'Known',
 'Walterbell',
 'Stevekemp',
 'Tkpitts',
 'Agsw',
 'Stevegreen88',
 'Sandmansandine',
 'Dvdhsu',
 'Baristageek',
 'Adamnemecek',
 'Jseliger',
 'Altstar',
 'Pcl',
 'Okket',
 'Cubinho',
 'Aaron695',
 'Ryan_j_naughton',
 'Ryan_j_naughton',
 'Mynameislegion',
 'Rkan',
 'Gexos',
 'Kornish',
 'Dsteinmann',
 'Hitr',
 'Meowface',
 'Tomrod',
 'My_first_acct',
 'Halienja',
 'Halienja',
 'Halienja',
 'Halienja',
 'Colinprince',
 'Gexos',
 'Okket',
 'Subliminalpanda',
 'Aburan28',
 'Ralfd',
 'Cprecioso',
 'Upen',
 'Aidenlivingston',
 'Josephscott',
 'Bane',
 'Msabalau',
 'Eplanit',
 '1bytebeta',
 'Capitalistcartr',
 'Amluto',
 'Musik_padonur',
 'Mariobyn',
 'Bojanbabic',
 'Mhxnet',
 'Dkarapetyan',
 'Perseusprime11',
 'Devereaux',
 'Cskau',
 'Archgoon',
 'Type0',
 'Jernst',
 'Goodcanadian',
 'Rspivak',
 '0xffc',
 'Kornish',
 'Hvo',
 'Iamjeff',
 'Iamjeff',
 'Yani',
 'Hooke',
 'Jerry2',
 'Devine_sparkles',
 'Mpweiher',
 'Peterkshultz',
 'Type0',
 'Peeyek',
 'Neeleshs',
 'Campuscodi',
 'Mz',
 'Danso',
 'Drewrwx',
 'Bazillion',
 'Weatherlight',
 'Dnetesn',
 'Dnetesn',
 'Type0',
 'Johnreagan',
 'Eca',
 'Legodt',
 'Funkaster',
 'Onlydole',
 'Jonbaer',
 'Ddebernardy',
 'Type0',
 '2510c39011c5',
 'Funkaster',
 'Jensrantil',
 'Okket',
 'Dejital',
 'Jensrantil',
 'Jv22222',
 'Lxr',
 'Altstar',
 'Antonej',
 'Lforlambda',
 'Jasamba',
 'Futurebot',
 'Actuallyalys',
 'Sahil2305dua',
 'Yeroniomus',
 'Franzb',
 'Openmosix',
 'Gerardforde',
 'Dragonbonheur',
 'Helloworld',
 'Mz',
 'Minch',
 'Jensrantil',
 'X43b',
 'Daschaefer',
 'Splawn',
 'Okket',
 'Fune',
 'Toennisforst',
 'Phaas',
 'Gerardforde',
 'Gauto',
 'Walterbell',
 'Vmorgulis',
 'Wallflower',
 'Julienrbrt',
 'Cosmoharrigan',
 'Astrojetson',
 'Janisz',
 'Ourmandave',
 'Jdmoreira',
 'Michaelao',
 'Danielbmarkham',
 'Someone',
 'Olalonde',
 'Guessmyname',
 'Bijection',
 'Guessmyname',
 'Hackerkid',
 'Jarred',
 'Sndean',
 'Sea6ear',
 'Nvarsj',
 'Sapphiresun',
 'Jijojv',
 'Endswapper',
 'Zerognowl',
 'Jkuria',
 'Jkuria',
 'El_benhameen',
 'Oneeyedpigeon',
 'Walterbell',
 'Ra_fisher',
 'Surganov',
 'Stolk',
 'Svenfaw',
 'Burritofanatic',
 'Jonsouth',
 'Muhic',
 'Eagertolearn',
 'Archdesk',
 'Ganadiniakshay',
 'Fargo',
 'Muhic',
 'Lukaszwiktor',
 'Triplesec',
 'Surya_singh',
 'N457',
 'Punnerud',
 'Preetish',
 'Ldenoue',
 'Michaelao',
 'Punnerud',
 'Wolfgke',
 'Punnerud',
 'Lpellegr',
 'Molecule',
 'Giis',
 'Xpepper',
 'Traviswingo',
 'Jnajera1961',
 'Lillipaint',
 'Sankalp_sans',
 'Connorpjennings',
 'Thoughtfox',
 'Unsignedqword',
 'Sndean',
 'Norswap',
 'Houshuang',
 'Ingve',
 'Edamexxx',
 'Mz',
 'Mpweiher',
 'Sgt',
 'Lufficc',
 'Mattw1810',
 'Rspivak',
 'Lisper',
 'Igorpartola',
 'Joeyespo',
 'Rspivak',
 'Efavdb',
 'Jfdi',
 'Babich',
 'Danielam',
 'Miraj',
 'Punnerud',
 'Mpweiher',
 'Pointfree',
 'Networked',
 'Vezycash',
 'Fitzwatermellow',
 'Vezycash',
 'Ksherlock',
 'Networked',
 'Kamalkishor1991',
 'Prismatic',
 'Red_tarsius',
 'Kexari',
 '_ology',
 'Tokai',
 'Nols',
 'Jnordwick',
 'Endswapper',
 'Endswapper',
 'Jkuria',
 'Jnordwick',
 'Pdeva1',
 'Lunayo',
 'Scirocco',
 'Tomte',
 'Christophe971',
 'Tadruj',
 'Evo_9',
 'Hooke',
 'Striking',
 'Mz',
 'Mz',
 'Silvialisam',
 'Chestnut-tree',
 'Wslh',
 'Sua_3000',
 'Wanderer42',
 'Curtis',
 'Peterbsmith',
 'Silvialisam',
 'Jackgavigan',
 'Paulsutter',
 'Colinprince',
 'Tomte',
 'Tomte',
 'Tomte',
 'Jonbaer',
 'Jonbaer',
 'Mrb',
 'Lelf',
 'Mhxnet',
 'Sarkarsh',
 'Mathgenius',
 'Geerlingguy',
 'B-scan',
 'Master_yoda_1',
 'Endswapper',
 'Ozy',
 'Kelvl',
 'Mmastrac',
 'Galfarragem',
 'Jgrahamc',
 'Danielvf',
 'Svenfaw',
 'Pepys',
 'T0mek',
 'Snehesht',
 'Egjerlow',
 'Bane',
 'M52go',
 'Compil3r',
 'Anilkumarg',
 'Endianswap',
 'Cristiantincu',
 'Kbr',
 'Aj_jaswanth',
 'Ohjeez',
 'Natashabaker',
 'Scotrix',
 'Tambourine_man',
 'Ohjeez',
 'Ciphpercoder',
 'Khoury',
 'Azuajef',
 'Hollaur',
 'Sanqui',
 'Edsouza',
 'Markjohnson1',
 'Cjus',
 'Ourmandave',
 'Dreadfort',
 'Jonbaer',
 'Firasd',
 'Nathantross',
 'Zhenjl',
 'Lpellegr',
 'Colinprince',
 'Mdani',
 'Ohjeez',
 'Mdni007',
 'Joeyespo',
 'Jasim',
 'Zxcvvcxz',
 'Fredfisch',
 'Xoher',
 'Rkan',
 'Shidhincr',
 'Punnerud',
 'Based2',
 'Douche',
 'Darkcontinent',
 'Mattasher',
 'Sopmac21379',
 'Based2',
 'Azuajef',
 'Obi1kenobi',
 'Quickben',
 'Okket',
 'Kixpanganiban',
 'Dewey',
 'Cjbenedikt',
 'Design7',
 'Ting_bu_dung',
 'Nurdok',
 'Mignev',
 'Based2',
 'Obi1kenobi',
 'Illaigescheit',
 'M_grey',
 'Danarmak',
 'Based2',
 '5partan',
 'Fredrivett',
 'Based2',
 'Franciscop',
 'B01t',
 'Based2',
 'Endswapper',
 'Donzo',
 'Upen',
 'Wanderer42',
 'Endswapper',
 'Mwidell',
 'Kamranahmed_se',
 'Based2',
 'Sam42',
 'Guessmyname',
 'Endswapper',
 'Based2',
 'Chwolfe',
 'Endswapper',
 'Tiffanyricks',
 'Based2',
 'Based2',
 'Based2',
 'Pointillistic',
 'Clouddrover',
 'Endswapper',
 'Based2',
 'Endswapper',
 'Abula',
 'Mantesso',
 'Upen',
 'I_have_to_speak',
 'Design7',
 'Oliverjones',
 'Voctor',
 'Pdpi',
 'Jsudhams',
 'Dyates',
 'Based2',
 'Alex_hirner',
 'Jsnell',
 'Ourmandave',
 'Magicbuzz',
 'Bstanimirov',
 'Maxds',
 'Gioscarab',
 'Kardashian007',
 'Pascalprecht',
 'Arnebab',
 'Based2',
 'Networked',
 'Samber',
 'Samber',
 'Okket',
 'Linx',
 'Known',
 'Diablod3',
 'Arnoldsmith771',
 'Signa11',
 'Mynameislegion',
 'Jonbaer',
 'Diablod3',
 'Known',
 'Jonbaer',
 'Jonbaer',
 'Dushanr',
 'Velmu',
 'Radmuzom',
 'Txutxu',
 'Speckz',
 'Dnetesn',
 'Dnetesn',
 'Carolinew',
 'Glaberficken',
 'Erikstarck',
 'Joubert',
 'Stevemao',
 'Zo1',
 'Matvp',
 'Tete',
 'Dr1337',
 'Anchor',
 'Cozumel',
 'Lpellegr',
 'Carolinew',
 'Hankache',
 'Heinrichf',
 'Piedradura',
 'Mariusavram',
 'Kenting',
 'Mandatum',
 'Ytch',
 'Teammcs',
 'Uzzielnewton',
 'Walterbell',
 'Joubert',
 'Hgarg',
 'Zo1',
 'Topsmnews',
 'Walterbell',
 'N_yuichi',
 'Varek',
 'Sambeau',
 'Kevindeasis',
 'Stardotstar',
 'Chriscarex',
 'Parbeyjr',
 'Bozho',
 'Shpx',
 'Doppp',
 'Mynameislegion',
 'Mynameislegion',
 'Mynameislegion',
 'Silvialisam',
 'Silvialisam',
 'Nichodges',
 'Streamanalytix',
 'Gork',
 'Mynameislegion',
 'D99kris',
 'Mynameislegion',
 'Markjohnson1',
 'Ingve',
 'Dzhiurgis',
 'Wslh',
 'Mynameislegion',
 'Mpweiher',
 'Helloworld',
 'Jpenninkhof',
 'Antman',
 'Grimmdude',
 'Vsloo',
 'Pvsukale3',
 'Michaelao',
 'Firasd',
 'Stevewilhelm',
 'Mignev',
 'Betolink',
 'Luu',
 'Beardog',
 'Kp25',
 'Masteryupa_',
 'Mynameislegion',
 'Apsec112',
 'Bamunjal',
 'Sprucely',
 'Walterbell',
 'Noahgrant',
 'Kawera',
 'Attozk',
 'Sonabinu',
 'Breitling',
 'Rmason',
 'Walterbell',
 'Arinerron',
 'Keeperofdakeys',
 'Iamjeff',
 'Mmozeiko',
 'Iamjeff',
 'Sebg',
 'Deepakkarki',
 'Iamjeff',
 'Biackswan',
 'Tizzdogg',
 'Bane',
 'Akras14',
 'Joering2',
 'Denfromufa',
 'Sndean',
 'Mightybyte',
 'Johnhenry',
 'Rezist808',
 'Wallflower',
 'Traveltechguy',
 'Agsw',
 'Sndean',
 'Dwaxe',
 'Adamstauffer',
 'Danielam',
 'Wq',
 'Doubleguitars',
 'Lamito',
 'Dsr12',
 'Sloreti',
 'Olivercameron',
 'Rcthompson',
 'Perseusprime11',
 'Czarpino',
 'Unclebucknasty',
 'Ycnews',
 'Necessity',
 'Samber',
 'Jrbedard',
 'Cycomachead',
 'Daegloe',
 'Llsourcell',
 'Mentatghola',
 'Hoorayimhelping',
 'Benobringer',
 'Walterbell',
 'Modeless',
 'Pdkl95',
 'Maus42',
 'Jonbaer',
 'Silvialisam',
 'Mbradber',
 'Aoldoni',
 'Smdasilva',
 'Huhty',
 'Smilelogicortho',
 'Kbr',
 'Old_sound',
 ...]

In [22]:
df["Author"] =  lst

In [23]:
df.head()

,Id,Title,Url,Num_points,Num_comments,Author,Created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,Altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,Blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,Pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,Poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,Markgainor1,9/26/2016 3:14

In [24]:
df.tail()

,Id,Title,Url,Num_points,Num_comments,Author,Created_at
293114,10176919,Ask HN: What is/are your favorite quote(s)?,NaN,15,20,Kumarski,9/6/2015 6:02
293115,10176917,Attention and awareness in stage magic: turnin...,http://people.cs.uchicago.edu/~luitien/nrn2473...,14,0,Stakent,9/6/2015 6:01
293116,10176908,Dying vets fuck you letter (2013),http://dangerousminds.net/comments/dying_vets_...,10,2,Mycodebreaks,9/6/2015 5:56
293117,10176907,"PHP 7 Coolest Features: Space Ships, Type Hint...",https://www.zend.com/en/resources/php-7,2,0,Garbage,9/6/2015 5:55
293118,10176903,Toyota Establishes Research Centers with MIT a...,http://newsroom.toyota.co.jp/en/detail/9233109/,4,0,Tim_sw,9/6/2015 5:50

In [25]:
df["Url"]

0         http://www.regulations.gov/document?D=FDA-2015...
1          https://www.sqlite.org/sqlar/doc/trunk/README.md
2         https://medium.com/vanmoof/our-secrets-out-f21...
3         http://cacm.acm.org/magazines/2011/7/109891-al...
4         https://www.talend.com/blog/2016/05/12/talend-...
                                ...
293114                                                  NaN
293115    http://people.cs.uchicago.edu/~luitien/nrn2473...
293116    http://dangerousminds.net/comments/dying_vets_...
293117              https://www.zend.com/en/resources/php-7
293118      http://newsroom.toyota.co.jp/en/detail/9233109/
Name: Url, Length: 293119, dtype: object

In [31]:
df_date = []
df_month = []
df_year = []
df_time = []
lst_exception_rows = []
for i in df["Created_at"] :
    try :
        temp = i.split(" ")
        df_time.append(temp[1])
        temp = temp[0].split("/")
        df_month.append(temp[0])
        df_date.append(temp[1] )
        df_year.append(temp[2])
    except :
        lst_exception_rows.append(i)
lst_exception_rows

[]

In [33]:
df_time[:10]

['3:26',
 '3:24',
 '3:19',
 '3:16',
 '3:14',
 '3:13',
 '3:06',
 '3:04',
 '2:57',
 '2:56']

In [35]:
df_year[:10]

['2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016']

In [36]:
df_month[:10]

['9', '9', '9', '9', '9', '9', '9', '9', '9', '9']

In [38]:
df_date[:10]

['26', '26', '26', '26', '26', '26', '26', '26', '26', '26']

In [40]:
len(df_date) == len(df_month) == len(df_year) == len(df_month) == len(df)

True

In [41]:
df["Day"] = df_date
df["Month"] = df_month
df["Year"] = df_year
df["Time"] = df_time

In [42]:
df.head()

,Id,Title,Url,Num_points,Num_comments,Author,Created_at,Day,Month,Year,Time
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,Altstar,9/26/2016 3:26,26,9,2016,3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,Blacksqr,9/26/2016 3:24,26,9,2016,3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,Pavel_lishin,9/26/2016 3:19,26,9,2016,3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,Poindontcare,9/26/2016 3:16,26,9,2016,3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,Markgainor1,9/26/2016 3:14,26,9,2016,3:14

In [43]:
df["Year"].value_counts()

Year
2016    207184
2015     85935
Name: count, dtype: int64

In [44]:
df["Day"].value_counts()

Day
22    10675
15    10618
8     10559
11    10361
16    10358
9     10298
23    10272
18    10183
14    10099
7      9926
19     9906
12     9883
1      9846
21     9777
10     9742
17     9590
13     9534
20     9534
25     9524
29     9513
2      9406
6      9303
24     9291
5      8985
4      8833
3      8751
28     8689
26     8616
30     8214
27     8129
31     4704
Name: count, dtype: int64

In [45]:
df["Month"].value_counts()

Month
9     37160
10    24662
3     24481
2     24236
4     24108
5     23765
8     23731
1     23509
6     22966
11    21959
7     21461
12    21081
Name: count, dtype: int64

In [46]:
df["Num_points"].value_counts()

Num_points
1       96408
2       74756
3       36243
4       17221
5        9240
        ...
867         1
1296        1
735         1
812         1
739         1
Name: count, Length: 911, dtype: int64

In [48]:
df["Num_comments"].value_counts()

Num_comments
0      212718
1       28055
2        9731
3        5016
4        3272
        ...
868         1
631         1
581         1
446         1
842         1
Name: count, Length: 548, dtype: int64

In [49]:
df.to_csv("HN_Posts_CLEANED.csv",index= False)