In [59]:
from pandas import read_csv, isna

In [3]:
df = read_csv("Metro_Interstate_Traffic_Volume.csv")

In [4]:
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [5]:
df.tail()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
48199,NaN,283.45,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00,3543
48200,NaN,282.76,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00,2781
48201,NaN,282.73,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00,2159
48202,NaN,282.09,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00,1450
48203,NaN,282.12,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00,954

In [66]:
df.__len__()

48187

In [67]:
df.drop_duplicates(inplace= True)
df.reset_index(inplace= True)

In [68]:
df.__len__()

48187

In [9]:
df[isna(df["holiday"])].__len__()

48126

In [12]:
lst_column = []
for i in df.columns :
    lst_column.append(i.strip().capitalize() )
lst_column

['Holiday',
 'Temp',
 'Rain_1h',
 'Snow_1h',
 'Clouds_all',
 'Weather_main',
 'Weather_description',
 'Date_time',
 'Traffic_volume']

In [13]:
df.columns = lst_column

In [14]:
df.head()

,Holiday,Temp,Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Date_time,Traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [15]:
lst = []
for i in df["Holiday"] :
    if isna(i) :
        continue
    lst.append(i)
lst

['Columbus Day',
 'Veterans Day',
 'Thanksgiving Day',
 'Christmas Day',
 'New Years Day',
 'Washingtons Birthday',
 'Memorial Day',
 'Independence Day',
 'State Fair',
 'Labor Day',
 'Columbus Day',
 'Veterans Day',
 'Thanksgiving Day',
 'Christmas Day',
 'New Years Day',
 'Martin Luther King Jr Day',
 'Washingtons Birthday',
 'Memorial Day',
 'Independence Day',
 'State Fair',
 'Labor Day',
 'Columbus Day',
 'Veterans Day',
 'Thanksgiving Day',
 'Thanksgiving Day',
 'Christmas Day',
 'New Years Day',
 'New Years Day',
 'Washingtons Birthday',
 'Memorial Day',
 'Independence Day',
 'State Fair',
 'Labor Day',
 'Labor Day',
 'Columbus Day',
 'Veterans Day',
 'Thanksgiving Day',
 'Christmas Day',
 'Christmas Day',
 'New Years Day',
 'Martin Luther King Jr Day',
 'Martin Luther King Jr Day',
 'Washingtons Birthday',
 'Memorial Day',
 'Independence Day',
 'State Fair',
 'Labor Day',
 'Columbus Day',
 'Veterans Day',
 'Thanksgiving Day',
 'Christmas Day',
 'New Years Day',
 'Martin Luther King Jr Day',
 'Martin Luther King Jr Day',
 'Martin Luther King Jr Day',
 'Washingtons Birthday',
 'Memorial Day',
 'Independence Day',
 'State Fair',
 'Labor Day',
 'Labor Day']

In [16]:
# finding the column with nan values ...
lst_column_with_nan_values = []
for i in df.columns :
    if df[isna(df[i])].__len__() != 0 :
        lst_column_with_nan_values.append(i)
lst_column_with_nan_values

['Holiday']

In [17]:
lst = []
for i in df["Holiday"] :
    if(isna(i)) :
        lst.append("-")
    else :
        lst.append(i.capitalize())
lst

['-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 'Columbus day',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 '-',
 ...]

In [19]:
df["Holiday"] = lst

In [20]:
df.head()

,Holiday,Temp,Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Date_time,Traffic_volume
0,-,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,-,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,-,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,-,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,-,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [29]:
# converting the Temp column values to Temp in Kelvin, Fahrenheit and Celsius

def kelvin_to_celsius(kelvin : float) -> float :
    return round(kelvin - 273.15,3)

def kelvin_to_fahrenheit(kelvin: float) -> float:
    return round(kelvin * 1.8 - 459.67 , 3)

In [30]:
temp_celsius = []
temp_fahrenheit = []

for i in df["Temp"] :
    temp_celsius.append(kelvin_to_celsius(float(i)) )
    temp_fahrenheit.append(kelvin_to_fahrenheit(float(i)) )

In [32]:
temp_celsius

[15.13,
 16.21,
 16.43,
 16.98,
 17.99,
 18.57,
 20.02,
 20.71,
 20.99,
 19.95,
 17.82,
 16.23,
 15.46,
 14.01,
 12.3,
 11.48,
 10.32,
 8.03,
 7.94,
 6.38,
 5.47,
 5.08,
 4.97,
 9.33,
 18.82,
 20.08,
 21.16,
 22.02,
 21.98,
 20.51,
 17.5,
 15.04,
 13.95,
 13.1,
 12.11,
 11.4,
 10.32,
 10.02,
 8.89,
 8.54,
 8.17,
 7.59,
 7.42,
 8.71,
 11.83,
 16.03,
 18.4,
 21.82,
 23.23,
 24.17,
 25.02,
 24.91,
 24.52,
 23.21,
 20.7,
 19.28,
 18.62,
 18.21,
 17.97,
 17.48,
 17.31,
 16.11,
 10.06,
 9.09,
 8.54,
 7.42,
 6.87,
 6.96,
 6.85,
 7.38,
 8.28,
 8.63,
 8.76,
 8.58,
 8.27,
 7.72,
 7.0,
 6.63,
 6.5,
 6.07,
 5.91,
 5.66,
 5.4,
 5.44,
 3.84,
 3.2,
 2.25,
 2.02,
 1.84,
 1.94,
 3.73,
 4.89,
 5.93,
 6.97,
 7.1,
 6.85,
 5.91,
 5.76,
 5.24,
 5.01,
 5.01,
 4.78,
 3.75,
 3.19,
 2.96,
 2.58,
 2.5,
 2.36,
 1.9,
 1.62,
 1.62,
 2.4,
 3.09,
 3.86,
 4.28,
 5.3,
 6.12,
 6.12,
 6.29,
 6.17,
 6.12,
 4.96,
 3.64,
 2.58,
 1.73,
 0.77,
 -0.07,
 -0.53,
 -1.37,
 -2.1,
 -2.52,
 -2.82,
 -3.54,
 -3.14,
 -1.92,
 0.56,
 3.62,
 6.32,
 6.69,
 9.19,
 9.79,
 10.33,
 11.18,
 11.33,
 11.08,
 8.84,
 6.66,
 6.2,
 5.75,
 5.31,
 4.63,
 4.12,
 4.32,
 3.82,
 3.37,
 3.45,
 4.16,
 5.23,
 6.2,
 8.22,
 9.96,
 10.93,
 11.99,
 13.2,
 14.08,
 15.38,
 17.22,
 16.98,
 15.71,
 14.21,
 11.96,
 10.31,
 9.3,
 8.73,
 8.63,
 7.94,
 8.02,
 8.1,
 8.1,
 8.1,
 6.95,
 6.95,
 6.46,
 6.46,
 6.52,
 7.04,
 8.94,
 9.11,
 8.9,
 8.44,
 8.08,
 9.45,
 9.45,
 9.45,
 9.45,
 9.45,
 9.45,
 0.75,
 1.25,
 0.9,
 0.56,
 -0.49,
 -0.5,
 -0.63,
 2.04,
 2.19,
 10.95,
 10.95,
 10.63,
 10.37,
 10.17,
 8.91,
 8.8,
 8.66,
 9.01,
 9.38,
 10.76,
 11.49,
 11.46,
 10.03,
 9.11,
 7.62,
 5.38,
 4.49,
 4.75,
 5.03,
 6.14,
 7.3,
 7.8,
 8.59,
 8.69,
 9.3,
 9.05,
 8.39,
 7.06,
 9.05,
 -0.57,
 -1.09,
 -2.16,
 -2.86,
 -3.67,
 -3.88,
 -4.24,
 -4.17,
 -3.92,
 -0.54,
 3.63,
 6.07,
 7.2,
 8.66,
 9.9,
 10.81,
 11.38,
 11.29,
 10.49,
 8.7,
 8.23,
 8.69,
 9.08,
 9.03,
 9.34,
 9.39,
 9.43,
 9.08,
 8.93,
 9.08,
 9.09,
 9.09,
 9.09,
 9.28,
 9.28,
 9.28,
 9.18,
 9.18,
 9.67,
 9.67,
 10.18,
 10.18,
 10.18,
 10.6,
 10.6,
 10.6,
 10.94,
 10.94,
 10.94,
 11.4,
 11.4,
 11.53,
 11.49,
 11.49,
 11.25,
 11.02,
 10.88,
 10.43,
 9.89,
 8.8,
 8.8,
 8.46,
 8.46,
 8.42,
 8.27,
 8.14,
 8.14,
 7.87,
 7.87,
 7.67,
 7.67,
 7.24,
 7.04,
 6.67,
 6.6,
 6.92,
 7.17,
 8.57,
 10.86,
 12.73,
 13.72,
 14.45,
 14.12,
 13.03,
 12.05,
 11.53,
 11.34,
 10.39,
 9.18,
 8.06,
 6.72,
 5.78,
 4.76,
 4.06,
 3.46,
 2.96,
 1.66,
 1.84,
 4.76,
 7.56,
 10.7,
 12.86,
 13.16,
 15.0,
 16.0,
 15.84,
 15.71,
 15.01,
 14.13,
 13.89,
 13.75,
 13.94,
 13.94,
 13.74,
 13.78,
 13.78,
 13.92,
 13.41,
 12.76,
 12.14,
 11.77,
 12.2,
 12.57,
 12.57,
 13.94,
 15.16,
 15.46,
 17.17,
 18.21,
 18.86,
 19.46,
 19.5,
 17.37,
 15.2,
 13.57,
 12.34,
 11.07,
 10.65,
 10.57,
 9.65,
 9.17,
 9.23,
 9.61,
 9.73,
 11.03,
 11.54,
 11.85,
 13.75,
 15.2,
 16.44,
 15.12,
 13.26,
 12.81,
 13.89,
 14.03,
 13.79,
 12.86,
 11.52,
 10.29,
 9.36,
 8.75,
 8.7,
 8.13,
 7.82,
 7.29,
 7.29,
 6.87,
 6.64,
 6.64,
 6.64,
 6.64,
 6.59,
 6.59,
 6.5,
 6.5,
 6.5,
 6.3,
 6.3,
 6.07,
 6.07,
 6.07,
 6.2,
 6.2,
 6.77,
 7.29,
 7.85,
 8.36,
 8.78,
 8.79,
 8.79,
 9.12,
 9.26,
 9.06,
 8.54,
 8.11,
 7.51,
 7.28,
 7.28,
 6.95,
 6.95,
 6.95,
 6.91,
 6.91,
 7.13,
 7.13,
 7.23,
 7.47,
 7.47,
 7.76,
 7.76,
 7.76,
 7.81,
 7.81,
 7.81,
 7.98,
 7.98,
 7.98,
 8.13,
 8.13,
 8.13,
 8.04,
 8.04,
 8.04,
 8.55,
 8.55,
 8.55,
 8.55,
 8.87,
 8.87,
 8.87,
 8.87,
 9.2,
 9.2,
 9.2,
 9.56,
 9.56,
 9.56,
 9.56,
 10.16,
 10.64,
 11.05,
 11.17,
 10.98,
 9.99,
 8.25,
 7.32,
 6.37,
 5.7,
 4.97,
 4.79,
 2.78,
 2.78,
 10.94,
 9.45,
 8.57,
 8.11,
 8.14,
 7.86,
 7.42,
 7.39,
 6.22,
 6.03,
 5.9,
 9.55,
 13.02,
 15.46,
 17.44,
 19.06,
 20.41,
 20.28,
 20.25,
 18.32,
 16.02,
 14.13,
 12.95,
 12.3,
 12.18,
 11.92,
 11.43,
 10.73,
 10.4,
 9.7,
 9.27,
 8.98,
 8.7,
 8.7,
 9.92,
 11.38,
 12.45,
 13.48,
 13.6,
 14.82,
 15.39,
 15.57,
 15.38,
 15.01,
 14.44,
 14.06,
 13.14,
 12.55,
 12.46,
 12.22,
 12.22,
 12.36,
 12.45,
 12.84,
 12.84,
 12.79,
 12.79,
 12.82,
 12.82,
 12.82,
 12.58,
 12.58,
 12.58,
 12.58,
 12.35,
 12.35,
 12.4,
 12.4,
 12.4,
 12.4,
 12.78,
 12.78,
 12.78,
 13.19,
 13.67,
 13.67,
 15.21,
 15.21,
 15.21,
 15.93,
 15.93,
 15.93,
 16.73,
 16.73,
 17.09,
 17.09,
 17.09,
 16.86,
 16.47,
 16.47,
 16.46,
 16.46,
 15.91,
 15.19,
 15.19,
 13.91,
 14.26,
 14.37,
 14.66,
 14.14,
 14.08,
 13.29,
 12.17,
 12.17,
 12.28,
 12.38,
 12.05,
 12.05,
 11.87,
 13.28,
 14.21,
 14.45,
 14.14,
 13.26,
 13.26,
 13.26,
 13.26,
 12.65,
 12.65,
 12.65,
 12.65,
 12.65,
 12.14,
 12.14,
 12.14,
 11.62,
 11.62,
 11.62,
 11.14,
 11.14,
 11.14,
 11.14,
 10.64,
 10.64,
 10.64,
 10.29,
 10.29,
 10.29,
 10.07,
 10.07,
 10.07,
 9.67,
 8.98,
 7.9,
 7.9,
 7.9,
 7.29,
 7.29,
 6.92,
 6.92,
 6.92,
 6.39,
 6.39,
 6.39,
 6.39,
 5.78,
 5.78,
 5.78,
 5.78,
 5.78,
 5.12,
 5.12,
 5.12,
 5.12,
 4.92,
 4.92,
 4.92,
 4.38,
 4.38,
 3.08,
 3.08,
 3.08,
 2.51,
 2.51,
 2.51,
 1.87,
 1.87,
 1.87,
 1.87,
 1.88,
 1.88,
 1.88,
 1.88,
 1.35,
 1.35,
 1.86,
 2.23,
 2.23,
 2.7,
 3.41,
 3.55,
 3.56,
 3.28,
 3.08,
 2.84,
 3.13,
 3.13,
 2.86,
 2.21,
 1.78,
 1.13,
 0.86,
 0.56,
 0.28,
 0.5,
 1.43,
 2.24,
 2.29,
 2.96,
 3.33,
 3.35,
 3.41,
 3.46,
 3.75,
 3.46,
 3.19,
 2.81,
 2.45,
 1.71,
 0.9,
 0.47,
 0.37,
 0.39,
 0.48,
 0.48,
 0.07,
 -0.4,
 -0.99,
 -2.09,
 -2.47,
 -0.55,
 0.91,
 2.66,
 4.39,
 5.39,
 5.82,
 5.76,
 5.66,
 5.12,
 3.52,
 2.71,
 1.14,
 0.22,
 -0.38,
 -1.14,
 -1.37,
 -1.74,
 -1.69,
 -1.39,
 -0.91,
 -1.17,
 -1.62,
 -1.69,
 -1.45,
 0.11,
 1.75,
 3.18,
 4.43,
 5.35,
 6.15,
 6.74,
 6.96,
 6.67,
 5.54,
 4.6,
 3.62,
 3.46,
 2.91,
 2.07,
 1.6,
 1.09,
 0.32,
 0.35,
 0.0,
 -0.15,
 -0.46,
 -0.07,
 0.76,
 1.67,
 3.01,
 4.54,
 5.32,
 5.97,
 6.13,
 7.04,
 7.35,
 7.15,
 6.43,
 5.63,
 5.35,
 3.78,
 2.88,
 1.86,
 0.72,
 -0.16,
 -0.74,
 -0.84,
 -0.76,
 -1.42,
 -1.61,
 -2.03,
 -1.98,
 -0.04,
 2.86,
 5.12,
 6.69,
 7.53,
 8.07,
 8.65,
 9.05,
 8.33,
 6.85,
 5.33,
 3.71,
 2.3,
 0.9,
 -0.4,
 -1.42,
 -2.24,
 -3.0,
 -3.47,
 -3.71,
 -4.19,
 -4.54,
 -4.41,
 -4.7,
 -2.25,
 0.3,
 2.75,
 5.55,
 7.1,
 8.52,
 9.88,
 9.98,
 9.89,
 8.15,
 6.69,
 5.73,
 5.36,
 6.11,
 6.06,
 5.7,
 4.44,
 3.86,
 4.0,
 4.75,
 5.16,
 5.48,
 5.07,
 4.43,
 4.87,
 5.22,
 5.63,
 5.63,
 6.44,
 6.49,
 6.85,
 6.61,
 5.75,
 3.91,
 2.14,
 1.83,
 0.16,
 -0.38,
 -1.09,
 -1.14,
 -1.35,
 -1.85,
 -2.74,
 -3.25,
 -3.59,
 -3.76,
 -3.91,
 -4.16,
 -1.68,
 -0.3,
 0.78,
 1.7,
 2.28,
 2.58,
 2.75,
 3.14,
 3.26,
 3.14,
 2.98,
 2.78,
 2.78,
 2.52,
 2.43,
 2.52,
 2.45,
 2.62,
 2.27,
 2.32,
 2.18,
 1.93,
 1.93,
 1.94,
 1.94,
 2.29,
 2.95,
 3.3,
 3.61,
 3.96,
 4.98,
 5.29,
 5.29,
 4.94,
 4.57,
 4.26,
 4.05,
 3.91,
 3.55,
 3.39,
 2.92,
 2.52,
 1.82,
 1.71,
 0.3,
 -0.49,
 -0.97,
 -0.83,
 -0.46,
 1.11,
 2.84,
 4.2,
 4.68,
 5.32,
 5.56,
 7.41,
 7.41,
 6.11,
 7.41,
 7.41,
 7.41,
 7.41,
 7.41,
 1.26,
 1.26,
 1.26,
 1.26,
 1.26,
 1.26,
 1.76,
 1.76,
 1.76,
 1.76,
 3.97,
 4.89,
 5.04,
 5.23,
 5.44,
 5.5,
 5.59,
 5.59,
 5.72,
 5.72,
 5.87,
 5.87,
 5.69,
 5.69,
 5.69,
 5.41,
 5.41,
 5.41,
 5.35,
 5.35,
 4.88,
 4.88,
 4.88,
 4.13,
 4.13,
 3.91,
 3.91,
 3.91,
 3.91,
 3.68,
 3.68,
 3.68,
 4.0,
 4.0,
 4.42,
 4.42,
 4.36,
 4.36,
 4.36,
 4.26,
 4.26,
 4.53,
 4.53,
 5.0,
 5.27,
 5.46,
 5.99,
 5.84,
 5.68,
 5.42,
 5.42,
 5.06,
 5.06,
 5.06,
 5.06,
 4.81,
 4.81,
 4.36,
 4.03,
 3.93,
 3.83,
 3.78,
 3.61,
 3.64,
 3.49,
 ...]

In [47]:
df["Temp(in C)"] = temp_celsius
df["Temp(in F)"] = temp_fahrenheit

In [48]:
df.head()

,Holiday,Temp,Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Date_time,Traffic_volume,Temp(in C),Temp(in F)
0,-,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545,15.13,59.234
1,-,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516,16.21,61.178
2,-,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767,16.43,61.574
3,-,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026,16.98,62.564
4,-,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918,17.99,64.382

In [50]:
lst_column = list(df.columns )[:-2]
lst_column.insert(2,"Temp(in C)")
lst_column.insert(3,"Temp(in F)")
lst_column

['Holiday',
 'Temp',
 'Temp(in C)',
 'Temp(in F)',
 'Rain_1h',
 'Snow_1h',
 'Clouds_all',
 'Weather_main',
 'Weather_description',
 'Date_time',
 'Traffic_volume']

In [52]:
df = df.reindex(columns= lst_column )

In [53]:
df.tail()

,Holiday,Temp,Temp(in C),Temp(in F),Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Date_time,Traffic_volume
48199,-,283.45,10.30,50.540,0.0,0.0,75,Clouds,broken clouds,2018-09-30 19:00:00,3543
48200,-,282.76,9.61,49.298,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 20:00:00,2781
48201,-,282.73,9.58,49.244,0.0,0.0,90,Thunderstorm,proximity thunderstorm,2018-09-30 21:00:00,2159
48202,-,282.09,8.94,48.092,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 22:00:00,1450
48203,-,282.12,8.97,48.146,0.0,0.0,90,Clouds,overcast clouds,2018-09-30 23:00:00,954

In [54]:
df.rename(columns={"Temp" : "Temp(in K)"}, inplace= True)

In [55]:
df.head()

,Holiday,Temp(in K),Temp(in C),Temp(in F),Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Date_time,Traffic_volume
0,-,288.28,15.13,59.234,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,-,289.36,16.21,61.178,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,-,289.58,16.43,61.574,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,-,290.13,16.98,62.564,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,-,291.14,17.99,64.382,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [57]:
df["Weather_main"].value_counts()

Weather_main
Clouds          15158
Clear           13384
Mist             5949
Rain             5672
Snow             2875
Drizzle          1820
Haze             1360
Thunderstorm     1033
Fog               912
Smoke              20
Squall              4
Name: count, dtype: int64

In [61]:
df["Weather_description"].value_counts()

Weather_description
sky is clear                           11659
mist                                    5949
overcast clouds                         5079
broken clouds                           4663
scattered clouds                        3460
light rain                              3372
few clouds                              1956
light snow                              1945
Sky is Clear                            1725
moderate rain                           1664
haze                                    1360
light intensity drizzle                 1099
fog                                      912
proximity thunderstorm                   673
drizzle                                  651
heavy snow                               616
heavy intensity rain                     467
snow                                     293
proximity shower rain                    136
thunderstorm                             124
heavy intensity drizzle                   64
thunderstorm with heavy rain              63
thunderstorm with light rain              54
proximity thunderstorm with rain          52
thunderstorm with rain                    37
smoke                                     20
very heavy rain                           18
thunderstorm with light drizzle           15
light intensity shower rain               13
proximity thunderstorm with drizzle       13
light shower snow                         11
light rain and snow                        6
shower drizzle                             6
SQUALLS                                    4
sleet                                      3
thunderstorm with drizzle                  2
freezing rain                              2
shower snow                                1
Name: count, dtype: int64

In [62]:
lst = []
for i in df["Weather_description"] :
    lst.append(i.capitalize())
lst

['Scattered clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Sky is clear',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Scattered clouds',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Broken clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Scattered clouds',
 'Scattered clouds',
 'Sky is clear',
 'Sky is clear',
 'Scattered clouds',
 'Scattered clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Light rain',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Sky is clear',
 'Light rain',
 'Light intensity drizzle',
 'Light rain',
 'Light intensity drizzle',
 'Light rain',
 'Light intensity drizzle',
 'Sky is clear',
 'Sky is clear',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light intensity drizzle',
 'Light rain',
 'Light intensity drizzle',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Broken clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Sky is clear',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Mist',
 'Light intensity drizzle',
 'Mist',
 'Haze',
 'Light intensity drizzle',
 'Mist',
 'Light intensity drizzle',
 'Mist',
 'Mist',
 'Light rain',
 'Light intensity drizzle',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Mist',
 'Light rain',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Fog',
 'Mist',
 'Fog',
 'Fog',
 'Fog',
 'Mist',
 'Fog',
 'Mist',
 'Fog',
 'Mist',
 'Fog',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Overcast clouds',
 'Sky is clear',
 'Scattered clouds',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Few clouds',
 'Broken clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Sky is clear',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Light rain',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Proximity shower rain',
 'Light rain',
 'Broken clouds',
 'Broken clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Mist',
 'Mist',
 'Overcast clouds',
 'Mist',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light rain',
 'Overcast clouds',
 'Overcast clouds',
 'Light rain',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light intensity drizzle',
 'Light rain',
 'Light intensity drizzle',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Mist',
 'Light intensity drizzle',
 'Mist',
 'Mist',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Drizzle',
 'Mist',
 'Light rain',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Mist',
 'Moderate rain',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Light rain',
 'Mist',
 'Mist',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Mist',
 'Mist',
 'Light intensity drizzle',
 'Moderate rain',
 'Light rain',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Mist',
 'Drizzle',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Light intensity drizzle',
 'Light rain',
 'Moderate rain',
 'Drizzle',
 'Light rain',
 'Light intensity drizzle',
 'Light intensity drizzle',
 'Mist',
 'Mist',
 'Drizzle',
 'Light rain',
 'Light rain',
 'Mist',
 'Drizzle',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Light rain',
 'Mist',
 'Drizzle',
 'Light rain',
 'Mist',
 'Drizzle',
 'Light rain',
 'Drizzle',
 'Mist',
 'Light intensity drizzle',
 'Light rain',
 'Drizzle',
 'Mist',
 'Moderate rain',
 'Light rain',
 'Mist',
 'Drizzle',
 'Heavy intensity rain',
 'Mist',
 'Light rain',
 'Moderate rain',
 'Light rain',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Broken clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Few clouds',
 'Few clouds',
 'Mist',
 'Fog',
 'Mist',
 'Fog',
 'Mist',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Broken clouds',
 'Mist',
 'Mist',
 'Mist',
 'Sky is clear',
 'Scattered clouds',
 'Broken clouds',
 'Few clouds',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Few clouds',
 'Few clouds',
 'Broken clouds',
 'Scattered clouds',
 'Few clouds',
 'Broken clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Moderate rain',
 'Overcast clouds',
 'Proximity thunderstorm',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light intensity drizzle',
 'Mist',
 'Overcast clouds',
 'Haze',
 'Mist',
 'Haze',
 'Mist',
 'Proximity thunderstorm',
 'Mist',
 'Light rain',
 'Proximity thunderstorm',
 'Mist',
 'Thunderstorm with light rain',
 'Moderate rain',
 'Proximity thunderstorm',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Proximity thunderstorm',
 'Light intensity drizzle',
 'Mist',
 'Moderate rain',
 'Mist',
 'Mist',
 'Fog',
 'Mist',
 'Haze',
 'Fog',
 'Haze',
 'Mist',
 'Fog',
 'Mist',
 'Haze',
 'Mist',
 'Haze',
 'Moderate rain',
 'Mist',
 'Haze',
 'Mist',
 'Haze',
 'Mist',
 'Mist',
 'Haze',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Fog',
 'Mist',
 'Mist',
 'Mist',
 'Fog',
 'Mist',
 'Mist',
 'Mist',
 'Mist',
 'Overcast clouds',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Drizzle',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Drizzle',
 'Moderate rain',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Moderate rain',
 'Mist',
 'Light rain',
 'Light intensity drizzle',
 'Mist',
 'Moderate rain',
 'Light rain',
 'Light intensity drizzle',
 'Mist',
 'Light rain',
 'Light rain',
 'Mist',
 'Drizzle',
 'Moderate rain',
 'Mist',
 'Light intensity drizzle',
 'Overcast clouds',
 'Overcast clouds',
 'Light rain',
 'Moderate rain',
 'Light intensity drizzle',
 'Drizzle',
 'Light rain',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Drizzle',
 'Light rain',
 'Mist',
 'Moderate rain',
 'Light intensity drizzle',
 'Drizzle',
 'Heavy intensity rain',
 'Mist',
 'Moderate rain',
 'Proximity thunderstorm with rain',
 'Heavy intensity rain',
 'Mist',
 'Moderate rain',
 'Light rain',
 'Moderate rain',
 'Light rain',
 'Mist',
 'Moderate rain',
 'Light rain',
 'Mist',
 'Heavy snow',
 'Light rain',
 'Mist',
 'Moderate rain',
 'Heavy snow',
 'Light rain',
 'Heavy snow',
 'Mist',
 'Moderate rain',
 'Mist',
 'Heavy snow',
 'Heavy snow',
 'Heavy snow',
 'Mist',
 'Heavy snow',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Broken clouds',
 'Overcast clouds',
 'Sky is clear',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Haze',
 'Mist',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Heavy snow',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Broken clouds',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Broken clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light intensity drizzle',
 'Overcast clouds',
 'Haze',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Scattered clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Broken clouds',
 'Broken clouds',
 'Sky is clear',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Sky is clear',
 'Few clouds',
 'Broken clouds',
 'Broken clouds',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Few clouds',
 'Few clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Scattered clouds',
 'Scattered clouds',
 'Broken clouds',
 'Broken clouds',
 'Broken clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light rain',
 'Heavy snow',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light rain',
 'Overcast clouds',
 'Broken clouds',
 'Scattered clouds',
 'Few clouds',
 'Mist',
 'Few clouds',
 'Few clouds',
 'Sky is clear',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Sky is clear',
 'Mist',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Mist',
 'Mist',
 'Haze',
 'Mist',
 'Haze',
 'Mist',
 'Haze',
 'Mist',
 'Haze',
 'Heavy intensity drizzle',
 'Mist',
 'Haze',
 'Light rain',
 'Drizzle',
 'Haze',
 'Mist',
 'Haze',
 'Light rain',
 'Mist',
 'Light rain',
 'Mist',
 'Light rain',
 'Mist',
 'Moderate rain',
 'Snow',
 'Light rain',
 'Mist',
 'Moderate rain',
 'Light rain',
 'Mist',
 'Light rain',
 'Mist',
 'Light rain',
 'Mist',
 'Light intensity drizzle',
 'Light intensity drizzle',
 'Mist',
 'Mist',
 'Drizzle',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light rain',
 'Light rain',
 'Light intensity drizzle',
 'Light rain',
 'Mist',
 'Drizzle',
 'Light intensity drizzle',
 'Mist',
 'Moderate rain',
 'Mist',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 'Light rain',
 'Overcast clouds',
 'Overcast clouds',
 'Overcast clouds',
 ...]

In [63]:
df["Weather_description"] = lst

In [64]:
df["Weather_description"].value_counts()

Weather_description
Sky is clear                           13384
Mist                                    5949
Overcast clouds                         5079
Broken clouds                           4663
Scattered clouds                        3460
Light rain                              3372
Few clouds                              1956
Light snow                              1945
Moderate rain                           1664
Haze                                    1360
Light intensity drizzle                 1099
Fog                                      912
Proximity thunderstorm                   673
Drizzle                                  651
Heavy snow                               616
Heavy intensity rain                     467
Snow                                     293
Proximity shower rain                    136
Thunderstorm                             124
Heavy intensity drizzle                   64
Thunderstorm with heavy rain              63
Thunderstorm with light rain              54
Proximity thunderstorm with rain          52
Thunderstorm with rain                    37
Smoke                                     20
Very heavy rain                           18
Thunderstorm with light drizzle           15
Light intensity shower rain               13
Proximity thunderstorm with drizzle       13
Light shower snow                         11
Light rain and snow                        6
Shower drizzle                             6
Squalls                                    4
Sleet                                      3
Freezing rain                              2
Thunderstorm with drizzle                  2
Shower snow                                1
Name: count, dtype: int64

In [65]:
df.head()

,Holiday,Temp(in K),Temp(in C),Temp(in F),Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Date_time,Traffic_volume
0,-,288.28,15.13,59.234,0.0,0.0,40,Clouds,Scattered clouds,2012-10-02 09:00:00,5545
1,-,289.36,16.21,61.178,0.0,0.0,75,Clouds,Broken clouds,2012-10-02 10:00:00,4516
2,-,289.58,16.43,61.574,0.0,0.0,90,Clouds,Overcast clouds,2012-10-02 11:00:00,4767
3,-,290.13,16.98,62.564,0.0,0.0,90,Clouds,Overcast clouds,2012-10-02 12:00:00,5026
4,-,291.14,17.99,64.382,0.0,0.0,75,Clouds,Broken clouds,2012-10-02 13:00:00,4918

In [69]:
lst_date = []
lst_time = []
lst_exception_rows = []
for i in df["Date_time"] :
    try :
        x = str(i).strip().split(" ")
        lst_date.append(x[0])
        lst_time.append(x[1])
    except :
        lst_exception_rows.append(i)
lst_exception_rows

[]

In [72]:
df.__len__() == lst_date.__len__() == lst_time.__len__()

True

In [73]:
df["Date"] = lst_date
df["Time"] = lst_time

In [75]:
df.head()

,index,Holiday,Temp(in K),Temp(in C),Temp(in F),Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Date_time,Traffic_volume,Date,Time
0,0,-,288.28,15.13,59.234,0.0,0.0,40,Clouds,Scattered clouds,2012-10-02 09:00:00,5545,2012-10-02,09:00:00
1,1,-,289.36,16.21,61.178,0.0,0.0,75,Clouds,Broken clouds,2012-10-02 10:00:00,4516,2012-10-02,10:00:00
2,2,-,289.58,16.43,61.574,0.0,0.0,90,Clouds,Overcast clouds,2012-10-02 11:00:00,4767,2012-10-02,11:00:00
3,3,-,290.13,16.98,62.564,0.0,0.0,90,Clouds,Overcast clouds,2012-10-02 12:00:00,5026,2012-10-02,12:00:00
4,4,-,291.14,17.99,64.382,0.0,0.0,75,Clouds,Broken clouds,2012-10-02 13:00:00,4918,2012-10-02,13:00:00

In [79]:
df.drop(columns = ["Date_time" ,"index"],inplace= True)

In [80]:
df.head()

,Holiday,Temp(in K),Temp(in C),Temp(in F),Rain_1h,Snow_1h,Clouds_all,Weather_main,Weather_description,Traffic_volume,Date,Time
0,-,288.28,15.13,59.234,0.0,0.0,40,Clouds,Scattered clouds,5545,2012-10-02,09:00:00
1,-,289.36,16.21,61.178,0.0,0.0,75,Clouds,Broken clouds,4516,2012-10-02,10:00:00
2,-,289.58,16.43,61.574,0.0,0.0,90,Clouds,Overcast clouds,4767,2012-10-02,11:00:00
3,-,290.13,16.98,62.564,0.0,0.0,90,Clouds,Overcast clouds,5026,2012-10-02,12:00:00
4,-,291.14,17.99,64.382,0.0,0.0,75,Clouds,Broken clouds,4918,2012-10-02,13:00:00

In [81]:
df.to_csv("CLEANED_Metro_Interstate_Traffic_Volume.csv", index= False)